name: Atualizar GitHub Readme Stats

# Quando rodar:
on:
  schedule:
    - cron: '0 * * * *'  # roda a cada hora
  workflow_dispatch:     # permite rodar manualmente

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar GitHub Stats
        uses: anuraghazra/github-readme-stats@v0.4.3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          username: matheusraiano
          count_private: true
          include_all_commits: true
          theme: buefy
          output_file: stats.svg  # salva a imagem no repositório

      - name: Gerar Top Languages
        uses: anuraghazra/github-readme-stats@v0.4.3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          username: matheusraiano
          count_private: true
          layout: compact
          theme: buefy
          output_file: top-langs.svg

      - name: Commitar e enviar alterações
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg top-langs.svg
          git commit -m "Atualizar stats do GitHub" || echo "Sem alterações para commitar"
          git push